# Canonical license fingerprint metadata for MANIFEST/license-spdx-match.
#
# theatron is dual-licensed Apache-2.0 OR MIT. The kanon basanos
# CANONICAL_HASHES table does not include this dual-license combo,
# so this fingerprint file declares the SHA256 of theatron's
# repo-root LICENSE file directly.
#
# Workflow: if LICENSE is updated, recompute via `sha256sum LICENSE`
# and update the hash below.

[sha256]
LICENSE = "35b128f73616b8294c1de04ce59801160ada359fb9ca5878864ddf7f7ec253e0"
