name: Security
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # NOTE: Daily at 05:23 CST (11:23 UTC).
    - cron: "23 11 * * *"
  workflow_dispatch:
jobs:
  call:
    uses: forkwright/.github/.github/workflows/security.yml@main
    secrets: inherit
    with:
      runner: self-hosted
      has_private_deps: true
