name: Stale

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  stale:
    uses: forkwright/.github/.github/workflows/stale.yml@961f4e0d8ef84ac93303e9fb1ea4123c98b5dab1
