name: Stale

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  stale:
    uses: forkwright/.github/.github/workflows/stale.yml@66867bca65b34a464f184cf1d6d5c9ee433c4dba
